version: "3.9"

services:
  image_processor:
    build: ./image_processor
    env_file: .env
    networks:
      - app-network

  car_counter:
    build: ./car_counter
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    external: true