version: "3.9"

services:
  image-processor:
    build: ./Image_Processing/Image_Processor
    networks:
      - cv-network
    env_file:
      - ./Image_Processing/.env
    environment:
      - KAFKA_BOOTSTRAP=kafka:29092
      - TOPIC=cctv-image-events
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET=camera-images
      - CAR_COUNTER_URL=http://car-counter:5001/process
    
    depends_on:
      - minio
      - kafka


  car-counter:
    build: ./Image_Processing/Car_Counter
    networks:
      - app-network
      - cv-network
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET=camera-images
      - YOLO_ENDPOINT=https://nationally-cheerful-pegasus.ngrok-free.app/count_cars
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
    depends_on:
      - redis_parking_spots_status

  image-fetcher:
    build:
      context: ./Image_Processing/Image_Fetcher
    networks:
      - cv-network
    env_file:
      - ./Image_Processing/.env
    depends_on:
      - kafka
      - minio

  image-editor:
    build:
      context: ./Image_Processing/Image_Editor
    networks:
      - cv-network
    volumes:
      - ./Image_Processing/Image_Editor/textures:/app/textures
    env_file:
      - ./Image_Processing/.env
    depends_on:
      - minio


