apiVersion: 1

datasources:
- name: ClickHouse
  type: grafana-clickhouse-datasource
  access: proxy
  isDefault: true
  editable: true
  url: http://clickhouse:8123
  basicAuth: false
  user: parkman_user
  password: parkman_user_pass