
FROM apache/nifi:latest


COPY ./ApacheNifiETL/nifi-conf/nifi.properties /opt/nifi/current/conf/
COPY ./ApacheNifiETL/nifi-conf/nifi-users.xml /opt/nifi/current/conf/
COPY ./ApacheNifiETL/nifi-conf/login-identity-providers.xml /opt/nifi/current/conf/
COPY ./ApacheNifiETL/nifi-conf/authorizers.xml /opt/nifi/current/conf/
