global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'mongo_manager_db_service'
    static_configs:
      - targets: ['mongo_manager_db_service:27017']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
