import torch
from ultralytics import YOLO
import os
from itertools import product
import sys
import mlflow
import shutil
import boto3
import logging

# -----------------------------------------------------------------------------
# MLflow & MinIO Configuration
# -----------------------------------------------------------------------------

# 1. Set the Tracking URI to the exposed port of the MLflow server
mlflow.set_tracking_uri("http://localhost:5000")

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("train.log"),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

# 2. Set S3/MinIO Environment Variables for Artifact Uploads
# The client (this script) needs to know how to talk to MinIO to upload the model.
# NOTE: Ensure these credentials match what is inside ./S3Storage/minio.env
os.environ["MLFLOW_S3_ENDPOINT_URL"] = "http://localhost:9901"  # Port 9901 is mapped in your docker-compose
os.environ["AWS_ACCESS_KEY_ID"] = "minioadmin"      # Default MinIO user
os.environ["AWS_SECRET_ACCESS_KEY"] = "minioadmin"  # Default MinIO password
os.environ["MLFLOW_S3_IGNORE_TLS"] = "true"

# Ensure the MLflow bucket exists in MinIO
try:
    s3 = boto3.client('s3', endpoint_url=os.environ["MLFLOW_S3_ENDPOINT_URL"])
    bucket_name = "mlflow"
    if not any(b['Name'] == bucket_name for b in s3.list_buckets().get('Buckets', [])):
        logger.info(f"Creating S3 bucket: {bucket_name}")
        s3.create_bucket(Bucket=bucket_name)
except Exception as e:
    logger.warning(f"Warning: Attempt to check/create S3 bucket failed: {e}")

# 3. Set the Experiment Name
mlflow.set_experiment("YOLO_ParkMan_Training")

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
logger.info(f"Using device: {device}")

data_yaml_path = './VisDrone/data-visdrone.yaml'

param_grid = {
    'epochs': [10],
    'imgsz': [640],
}

# -----------------------------------------------------------------------------
# Training Loop
# -----------------------------------------------------------------------------

if not os.path.exists(data_yaml_path):
    logger.error(f"Error: {data_yaml_path} not found. Please make sure your dataset is correctly placed.")
else:
    for epochs, imgsz in product(param_grid['epochs'], param_grid['imgsz']):
        
        # Define a run name for MLflow
        run_name = f"yolo11m_e{epochs}_img{imgsz}"
        
        # Start an MLflow Run
        with mlflow.start_run(run_name=run_name) as run:
            
            # 1. Log Parameters
            mlflow.log_params({
                "epochs": epochs,
                "imgsz": imgsz,
                "batch_size": 4,
                "model_type": "yolo11m",
                "data_yaml": data_yaml_path,
                "device": str(device)
            })
            
            # 2. Log Dataset Configuration (Versioning)
            mlflow.log_artifact(data_yaml_path, artifact_path="dataset_config")

            logger.info(f'_____________________\nepoch: {epochs}, imgsz: {imgsz}, batch: 4____________________\n\n\n')
            
            model = YOLO('./yolo11m.pt')

            try:
                # Train the model
                # disable  ultralytics mlflow integration to avoid conflicts,
                
                results = model.train(
                    data=data_yaml_path, 
                    epochs=epochs, 
                    imgsz=imgsz, 
                    batch=4, 
                    patience=epochs//2, 
                    single_cls=True,
                    project="runs/train",
                    name=run_name
                )

                # 3. Log Metrics
                # results.results_dict contains final metrics (mAP, loss, etc.)
                if hasattr(results, 'results_dict'):
                    # Clean keys (remove parenthesis) for cleaner MLflow UI
                    metrics = {k.replace('(', '_').replace(')', ''): v for k, v in results.results_dict.items()}
                    mlflow.log_metrics(metrics)

                # 4. Log Artifacts (Model Weights & Plots)
                # Log the best model weights
                if hasattr(model.trainer, 'best'):
                    mlflow.log_artifact(model.trainer.best, artifact_path="weights")
                
                # Log training plots (confusion matrix, results.png, etc.) generated by YOLO
                save_dir = model.trainer.save_dir
                for file_name in os.listdir(save_dir):
                    if file_name.endswith('.png') or file_name.endswith('.jpg') or file_name.endswith('.csv'):
                        mlflow.log_artifact(os.path.join(save_dir, file_name), artifact_path="plots")

                logger.info(f"Training results saved to: {save_dir}")

            except Exception as e:
                logger.error(f"Error: {e}")
                mlflow.log_param("error", str(e))

# -----------------------------------------------------------------------------
# Post-Training (Optional: Save best of last run to Drive/Local)
# -----------------------------------------------------------------------------

# Note: 'model' variable holds the last trained model in the loop. 
#if 'model' in locals() and hasattr(model.trainer, 'best'):
 #   best_weights_path = model.trainer.best
  #  drive_save_path = './yolo11m_parkman_weights.pt'
   # shutil.copy(best_weights_path, drive_save_path)
   # print(f"Last run weights saved to disk at: {drive_save_path}")
